server:
    http_listen_address: 127.0.0.1
    http_listen_port: 9080
    grpc_listen_port: 0

positions:
    filename: /var/log/promtail/positions.yaml # This location needs to be writeable by Promtail.

client:
    url: http://127.0.0.1:3100/loki/api/v1/push

scrape_configs:
    - job_name: laravel
      static_configs:
          - targets:
                - localhost
            labels:
                job: laravel
                __path__: "/var/www/test-correct/storage/logs/loki.log"
      pipeline_stages:
          - json:
                expressions:
                    message: message
                    level: level_name
                    context: context
                    timestamp: datetime
                    user_id: user_id
                    ip: ip
                    role: role
                    request_method: request_method
          - timestamp:
                source: timestamp
                format: RFC3339Nano
    - job_name: auth
      static_configs:
          - targets:
                - localhost
            labels:
                job: auth
                __path__: "/var/log/auth.log"
