pipelines:
    custom:
        deploy-to-testportal:
            - step:
                  name: Deploy to testportal
                  image: composer:latest
                  clone:
                      enabled: false
                  deployment: testportal
                  script:
                      - apt-get update
                      - apt-get -y install git
                      - git clone ssh://git@bitbucket.org/teachandlearncompany/tlc-deploy
                      - cd tlc-deploy
                      - composer install
                      - ssh webdev@thetr-7.vm.bit.nl "id"
