<?php
return [
    'Beste'                                                                                                                                                                                                                                                                                                                                                                                           => 'Best',
    'Welkom bij Test-Correct'                                                                                                                                                                                                                                                                                                                                                                         => 'Welcome to Test-Correct',
    'Leuk dat je gaat werken in Test-Correct. Niets staat je nog in de weg om betere resultaten te behalen. Je actieve bijdrage bij het bespreken van de toets gaat ervoor zorgen dat jij veel meer gaat begrijpen en onthouden, de automatische analyse wijst je ook nog eens op je sterktes en zwaktes! Een goede voorbereiding voor ieder examen. Niets staat een prachtig diploma nog in de weg'  => 'Nice that you are going to work in Test-Correct. Nothing stands in the way of achieving better results. Your active contribution in discussing the test will ensure that you will understand and remember much more, the automatic analysis also points out your strengths and weaknesses! Good preparation for every exam. Nothing stands in the way of a beautiful diploma',
    'Je gebruikersnaam'                                                                                                                                                                                                                                                                                                                                                                               => 'Your username',
    'Je wachtwoord'                                                                                                                                                                                                                                                                                                                                                                                   => 'your password',
    'Lees deze tips voordat je aan de slag gaat'                                                                                                                                                                                                                                                                                                                                                      => 'Read these tips before you get started',
    'Toets maken'                                                                                                                                                                                                                                                                                                                                                                                     => 'Take a test',
    'CO-Learning'                                                                                                                                                                                                                                                                                                                                                                                 => 'CO-Learning',
    'Analyseren'                                                                                                                                                                                                                                                                                                                                                                                      => 'Analyze',
    'Bekijk wat je kan verwachten bij het maken van een toets in Test-Correct'                                                                                                                                                                                                                                                                                                                        => 'See what you can expect when taking a test in Test-Correct',
    'Hier zit het geheim van jouw succes. Bekijk waarom'                                                                                                                                                                                                                                                                                                                                              => 'Here is the secret to your success. See why',
    'Wat zeggen de analyses over jouw'                                                                                                                                                                                                                                                                                                                                                                => 'What do the analyzes say about you',
    'Veel plezier met Test-Correct & succes met de toetsen'                                                                                                                                                                                                                                                                                                                                           => 'Have fun with Test-Correct & good luck with the tests',
    'Test-Correct supportteam'                                                                                                                                                                                                                                                                                                                                                                        => 'Test-Correct support team',
    'Leuk dat je gaat werken in Test-Correct. Niets staat je nog in de weg om betere resultaten te behalen. Je actieve bijdrage bij het bespreken van de toets gaat ervoor zorgen dat jij veel meer gaat begrijpen en onthouden, de automatische analyse wijst je ook nog eens op je sterktes en zwaktes! Een goede voorbereiding voor ieder examen. Niets staat een prachtig diploma nog in de weg!' => 'Nice that you are going to work in Test-Correct. Nothing stands in the way of achieving better results. Your active contribution in discussing the test will ensure that you will understand and remember much more, the automatic analysis also points out your strengths and weaknesses! Good preparation for every exam. Nothing stands in the way of a beautiful diploma!',
    'Je gebruikersnaam:'                                                                                                                                                                                                                                                                                                                                                                              => 'Your username:',
    'Je kunt je wachtwoord instellen op:'                                                                                                                                                                                                                                                                                                                                                             => 'You can set your password on:',
    'Deze link verloopt vier uur nadat dit e-mailbericht werd verstuurd. Je kunt een nieuwe link laten opsturen via de wachtwoord vergeten functionaliteit.'                                                                                                                                                                                                                                          => 'This link will expire four hours after this email is sent. You can have a new link sent via the forgot password functionality.',
    'Nieuwe verzoek opsturen'                                                                                                                                                                                                                                                                                                                                                                         => 'Send new request'
];

