<?php
namespace tcCore\FactoryScenarios;

use Carbon\Carbon;
use Database\Seeders\NationalItemBankShortSeeder;
use Illuminate\Support\Collection;
use tcCore\Factories\FactoryBaseSubject;
use tcCore\Factories\FactorySchool;
use tcCore\Factories\FactorySchoolLocation;
use tcCore\Factories\FactorySchoolYear;
use tcCore\Factories\FactorySection;
use tcCore\Factories\FactoryTest;
use tcCore\Http\Helpers\ActingAsHelper;
use tcCore\School;
use tcCore\User;

class FactoryScenarioSchoolSimpleWithSmallNationalItemBank extends FactoryScenarioSchoolSimple
{
    public function __construct()
    {
        parent::__construct();
    }

    public static function create()
    {
        $instance = parent::create(); // TODO: Change the autogenerated stub
        $instance->seedNationalItemBank();
        return $instance;
    }


    public function getData()
    {
        return array_merge(
            parent::getData(), [
        ]);
    }

    private function seedNationalItemBank(){
        (new NationalItemBankShortSeeder)->run($this->getData()['user']);
        ActingAsHelper::getInstance()->reset();
        $this->getData()['user']->schoolLocation()->update(['show_national_item_bank' => true]);
    }
}
