<?php
/**
 * Created by PhpStorm.
 * User: erik
 * Date: 12/04/2019
 * Time: 13:18
 */

namespace Tests\Unit\Providers;

use Illuminate\Support\Str;
use Tests\TestCase;

class StrHelperMacroTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @dataProvider wordCountDataProvider
     * @test
     */
    public function canCountWordsOfStrings($string, $expectedCount)
    {
        $this->assertEquals($expectedCount, Str::plainTextWordCount($string));
    }

    /**
     * @dataProvider accentsCharactersProvider
     * @test
     */
    public function canCountWordsWithAccents($subString)
    {
        $string = sprintf('one two three %s five', $subString);

        $this->assertEquals(5, Str::plainTextWordCount($string));

        $string = sprintf('one two three f%sour five', $subString);

        $this->assertEquals(5, Str::plainTextWordCount($string));
    }

    /**
     * Muli language string checked with WordCount plugin of Ckeditor5: 215 words
     * @test
     */
    public function canCountWordsEqualsToCkEditor5()
    {
        $string = "Le charmant café de la ville, nommé 'L'Éclat du Soleil', était célèbre pour son délicieux croissant au beurre. Chaque matin, Mme. Brûlé, âgée de 54 ans, s'y rendait pour savourer son café accompagné d'une pâtisserie exquise. In München, am schönen Ufer der Isar, fand ein großes Fest statt. Herr Müller, ein bekannter Wissenschaftler, sprach über 'Die Zukunft der Technologie - Visionen für 2050'. Es war eine inspirierende Rede, die viele junge Köpfe begeisterte. En la playa de Barcelona, los niños jugaban alegremente mientras las olas bañaban la orilla suavemente. '¡Cuidado con el agua!', gritaba la señora García, preocupada por sus pequeños nietos, Lucía y José, de 6 y 8 años respectivamente. Björn och Elsa bestämde sig för att besöka den historiska staden Gamla Stan i Stockholm. 'Det är verkligen en unik plats', sa Elsa, medan de vandrade genom de smala gatorna, beundrande de gamla byggnaderna och de färgglada husen. Il ristorante 'Gusto dell'Italia', famoso per la sua autentica pizza margherita, era il preferito di Giovanni, un giovane chef appassionato. 'La perfezione sta nei dettagli', esclamò, ammirando la crosta croccante e il sapore ricco del formaggio. No coração de Lisboa, numa tarde ensolarada, Ana encontrou um antigo livro numa pequena livraria escondida. 'Isto é uma verdadeira relíquia', pensou, enquanto folheava as páginas amareladas pela passagem do tempo.";

        $this->assertEquals(215, Str::plainTextWordCount($string));
    }

    /**
     * Valuta should be counted as 1 word
     * @test
     */
    public function canCountWordsWithValuta()
    {
        $string = "$100.00 €100,- $1.000,00 €1,000.- £9.999.999,-";

        $this->assertEquals(5, Str::plainTextWordCount($string));
    }

    /**
     * Dates like 01-01-90 or 25-12-2023 should be counted as 1 word
     * @test
     */
    public function canCountWordsWithDates()
    {
        $string = "15 jan 23, 25-12-2023, 01-01-90";

        $this->assertEquals(5, Str::plainTextWordCount($string));
    }

    public static function wordCountDataProvider() : array
    {
        return [
        'empty string' => [
            '<p>  </p>', 0,
        ],
        'string with no valid words' => [
            '<p> !@#$%^&*()_+{}:">? </p>', 0,
        ],
        'plain text' => [
            'one two three four five   ', 5,
        ],
        'plain text with numbers' => [
            'one two thr33 4 five   ', 5,
        ],
        'plain text with aphostrophe' => [
            "one s'y cafe's four L'Éclat   ", 5,
        ],
        'html encased sentence' => [
            '<p>one two three four five</p>', 5,
        ],
        'sentence with html entities and html tags #1' => [
            '<p>one two three four &eacute;&eacute;five </p>', 5,
        ],
        'sentence with html entities and html tags #2' => [
            '<p>one&nbsp;two&nbsp;three&nbsp;four&nbsp;five</p>', 5,
        ],
        // after stripping the </p><p>, the word before and after should both still be counted as 2 words:
        'sentence with two paragraphs without spaces in between' => [
            "<p>one</p><p>two</p><p>three</p><p>four</p><p>five</p>", 5,
        ],
        'words separated by dots' => [
            "one.two.three.four.five", 5,
        ],
        'words separated by commas' => [
            "one,two, three,four, five", 5,
        ],
        'words separated by special characters' => [
            "*one_two%three&four^five%", 5,
        ],
        //
        'word that exists only out of special character #1' => [
            "one two three &eacute; five", 5,
        ],
        'word that exists only out of special character #2' => [
            "<p>one two three &aacute; five</p>", 5,
        ],
        //&ensp; En space
        //&emsp; Em space
        //&thinsp; Thin space
        //&zwnj; Zero width non-joiner
        //&zwj; Zero width joiner
        'special space characters and special character word' => [
            "<p>one&emsp;two&ensp;three&zwnj;&aacute;&zwj;five</p>", 5,
        ],

        'spanish' => [
            "niños. '¡Cuidado con el agua!',", 5,
        ],
        'french' => [
            "célèbre nommé 'L'Éclat du Soleil',", 5,
        ],
        'german' => [
            "großes Herr Müller: 'für 2050'", 5,
        ],

        'valuta' => [
            "$100.00 €100,- $1.000,00 €1,000.- £9.999.999,-", 5,
        ],

    ];
    }

    public static function accentsCharactersProvider() : array
    {
        return [
            'normal character' => ['a'],
            'letter e accent' => ['é'],
            'letter e accent (html entity)' => ['&eacute;'],
            'letter e umlaut' => ['ë'],
            'letter e umlaut (html entity)' => ['&euml;'],
            'letter e grave' => ['è'],
            'letter e grave (html entity)' => ['&egrave;'],
            'letter a accent' => ['á'],
            'letter a accent (html entity)' => ['&aacute;'],
            'letter i accent' => ['í'],
            'letter i accent (html entity)' => ['&iacute;'],
            'letter o accent' => ['ó'],
            'letter o accent (html entity)' => ['&oacute;'],
            'letter u accent' => ['ú'],
            'letter u accent (html entity)' => ['&uacute;'],
            'letter n tilde' => ['ñ'],
            'letter n tilde (html entity)' => ['&ntilde;'],
            'letter c cedille' => ['ç'],
            'letter c cedille (html entity)' => ['&ccedil;'],
            'letter a umlaut' => ['ä'],
            'letter a umlaut (html entity)' => ['&auml;'],
            'letter b' => ['ß'],
            'letter b (html entity)' => ['&szlig;'],
        ];
    }
}
