<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Testing\TestResponse;
use tcCore\TemporaryLogin;
use tcCore\User;
use Tests\TestCase;

class CreateTemporaryLoginAndRedirectUserWithOptionsTest extends TestCase
{
//    use DatabaseTransactions;

    public $user, $options;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = User::find(1483);
        $this->options = TemporaryLogin::buildValidOptionObject('reason', 'too slow');
    }

    /**
     * @test
     */
    public function can_create_redirect_url_for_user()
    {
        $url = $this->user->getTemporaryCakeLoginUrl();

        $this->assertStringContainsString(config('app.url_login').'users/temporary_login', $url);
    }

    /**
     * @test
     */
    public function can_create_temporary_login_with_json_in_options()
    {
        $temporaryLogin = TemporaryLogin::createWithOptionsForUser('reason', ['too slow'], $this->user);

        $this->assertJson($temporaryLogin->options);
    }

    /**
     * @test
     */
    public function user_gets_redirected_with_temporary_login()
    {
        $response = new TestResponse($this->user->redirectToCakeWithTemporaryLogin($this->options));

        $response->assertRedirect();
    }

    /**
     * @test
     */
    public function can_create_temporary_login_record_with_options()
    {
        TemporaryLogin::createWithOptionsForUser('reason', 'too slow', $this->user);

        $temporaryLoginOptions = TemporaryLogin::getOptionsForUser($this->user);

        $this->assertJson($temporaryLoginOptions);
    }
}
