<?php

namespace Tests\Unit\FactoryTests\TestFactory;

use Illuminate\Foundation\Testing\DatabaseTransactions;
use Tests\ScenarioLoader;
use Illuminate\Foundation\Testing\RefreshDatabase;
use tcCore\Factories\FactoryEducationLevel;
use tcCore\FactoryScenarios\FactoryScenarioSchoolSimple;
use tcCore\User;
use Tests\TestCase;

class FactoryEducationLevelTest extends TestCase
{
    private mixed $user;
    protected $loadScenario = FactoryScenarioSchoolSimple::class;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = ScenarioLoader::get('user');
    }

    /** @test */
    public function can_get_education_levels_for_User()
    {
        $educationLevelsCollection = FactoryEducationLevel::getEducationLevelsForUser($this->user);

        $this->assertInstanceOf("Illuminate\Database\Eloquent\Collection", $educationLevelsCollection );
        $this->assertInstanceOf("tcCore\EducationLevel", $educationLevelsCollection->first() );
    }

    /** @test */
    public function can_get_first_education_level_for_User()
    {
        $educationLevelsModel = FactoryEducationLevel::getFirstEducationLevelForUser($this->user);

        $this->assertInstanceOf("tcCore\EducationLevel", $educationLevelsModel);
    }

    /** @test */
    public function can_get_random_education_level_for_User()
    {
        $educationLevelsModel = FactoryEducationLevel::getRandomEducationLevelForUser($this->user);

        $this->assertInstanceOf("tcCore\EducationLevel", $educationLevelsModel);
    }

}