<?php

namespace Tests\Unit\FactoryTests\TestFactory;

use Illuminate\Foundation\Testing\DatabaseTransactions;
use Tests\ScenarioLoader;
use tcCore\Factories\FactorySubject;
use tcCore\FactoryScenarios\FactoryScenarioSchoolSimple;
use tcCore\User;
use Tests\TestCase;

class FactorySubjectTest extends TestCase
{

    private mixed $user;
    protected $loadScenario = FactoryScenarioSchoolSimple::class;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = ScenarioLoader::get('user');
    }
    
    /** @test */
    public function can_get_subjects_for_User()
    {
        $userId = 1486;

        $subjectsCollection = FactorySubject::getSubjectsForUser($this->user);

        $this->assertInstanceOf("Illuminate\Database\Eloquent\Collection", $subjectsCollection );
        $this->assertInstanceOf("tcCore\Subject", $subjectsCollection->first() );
    }

    /** @test */
    public function can_get_first_subject_for_User()
    {
        $userId = 1486;

        $subjectsModel = FactorySubject::getFirstSubjectForUser($this->user);

        $this->assertInstanceOf("tcCore\Subject", $subjectsModel);
    }

    /** @test */
    public function can_get_random_subject_for_User()
    {
        $userId = 1486;

        $subjectsModel = FactorySubject::getRandomSubjectForUser($this->user);

        $this->assertInstanceOf("tcCore\Subject", $subjectsModel);
    }

}