<?php

namespace Tests\Unit\FactoryTests\TestFactory;

use Illuminate\Foundation\Testing\DatabaseTransactions;
use Tests\ScenarioLoader;
use tcCore\Factories\FactoryPeriod;
use tcCore\FactoryScenarios\FactoryScenarioSchoolSimple;
use tcCore\User;
use Tests\TestCase;

class FactoryPeriodTest extends TestCase
{

    private mixed $user;
    protected $loadScenario = FactoryScenarioSchoolSimple::class;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = ScenarioLoader::get('user');
    }
    
    /** @test */
    public function can_get_periods_for_User()
    {
        $periodsCollection = FactoryPeriod::getPeriodsForUser($this->user);

        $this->assertInstanceOf("Illuminate\Database\Eloquent\Collection", $periodsCollection );
        $this->assertInstanceOf("tcCore\Period", $periodsCollection->first() );
    }

    /** @test */
    public function can_get_first_period_for_User()
    {
        $periodsModel = FactoryPeriod::getFirstPeriodForUser($this->user);

        $this->assertInstanceOf("tcCore\Period", $periodsModel);
    }

    /** @test */
    public function can_get_random_period_for_User()
    {
        $periodsModel = FactoryPeriod::getRandomPeriodForUser($this->user);

        $this->assertInstanceOf("tcCore\Period", $periodsModel);
    }
}