<?php


namespace Tests\Unit\Http\Helpers;

use Illuminate\Foundation\Testing\DatabaseTransactions;
use tcCore\Http\Helpers\AnalysesGeneralDataHelper;
use tcCore\Subject;
use Tests\TestCase;

class AnalysesSubjectHelperTest extends TestCase
{
    use DatabaseTransactions;
    
    public $helper;
    
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        
        $this->helper = new AnalysesGeneralDataHelper(
            Subject::find(1),
            $this->getStudentOne()
        );
    }

    /** @test */
    public function can_do_something()
    {
        dd((array)$this->helper->getAllForSubject());
    }
}
