<?php
return [
    'Beste toetsenbakker'                                                                                                                                                                                                                                                            => 'Best testboard baker',
    'Er staat weer een toets voor je klaar om in te voeren'                                                                                                                                                                                                                          => 'Another test is ready for you to enter',
    'Aanleverdatum'                                                                                                                                                                                                                                                                  => 'Delivery date',
    'Docent'                                                                                                                                                                                                                                                                         => 'Lecturer',
    'Vak'                                                                                                                                                                                                                                                                            => 'Subject',
    'Naam'                                                                                                                                                                                                                                                                           => 'Name',
    'Je kunt inloggen met het account'                                                                                                                                                                                                                                               => 'You can log in with the account',
    'Voordat je start met het bakken van de toets, verander eerst de status naar �in behandeling\', ben je klaar verander de status naar �klaar voor eerste controle�. Wil je pauzeren en op een later moment verder met deze toets, verander de status in �behandeling gepauzeerd�' => 'Before you start baking the test, first change the status to "pending", you are done change the status to "ready for first check". If you want to pause and continue with this test at a later time, change the status to "treatment paused"',
    'Met een vriendelijke groet'                                                                                                                                                                                                                                                     => 'Yours sincerely',
    'Test-Correct supportteam'                                                                                                                                                                                                                                                       => 'Test-Correct support team'
];
