<?php
return [
    'Beste toetsenbakker'                                                                                                                                                                                                                                                            => 'Beste toetsenbakker',
    'Er staat weer een toets voor je klaar om in te voeren'                                                                                                                                                                                                                          => 'Er staat weer een toets voor je klaar om in te voeren',
    'Aanleverdatum'                                                                                                                                                                                                                                                                  => 'Aanleverdatum',
    'Docent'                                                                                                                                                                                                                                                                         => 'Docent',
    'Vak'                                                                                                                                                                                                                                                                            => 'Vak',
    'Naam'                                                                                                                                                                                                                                                                           => 'Naam',
    'Je kunt inloggen met het account'                                                                                                                                                                                                                                               => 'Je kunt inloggen met het account',
    'Voordat je start met het bakken van de toets, verander eerst de status naar �in behandeling\', ben je klaar verander de status naar �klaar voor eerste controle�. Wil je pauzeren en op een later moment verder met deze toets, verander de status in �behandeling gepauzeerd�' => 'Voordat je start met het bakken van de toets, verander eerst de status naar �in behandeling\', ben je klaar verander de status naar �klaar voor eerste controle�. Wil je pauzeren en op een later moment verder met deze toets, verander de status in �behandeling gepauzeerd�',
    'Met een vriendelijke groet'                                                                                                                                                                                                                                                     => 'Met een vriendelijke groet',
    'Test-Correct supportteam'                                                                                                                                                                                                                                                       => 'Test-Correct supportteam'
];
